### ISSUE TITLE
Update Project

### ISSUE THREAD

**Issue by rafaell-lycan** [gdg-sp/sabesp-live#1]
Update Project to last version with all this working and separated by step :see_no_evil:

**Comment by ubiratansoares** [comment]
@rafaell-lycan Done! :smile:

**Comment by rafaell-lycan** [comment]
:clap:

**Comment by rafaell-lycan** [comment]
@ubiratansoares qual o trampo pra fazer uma tela assim?

![](https://d13yacurqjgara.cloudfront.net/users/34934/screenshots/1342474/attachments/190234/Refill_Dribbble_Big.jpg)

**Comment by ubiratansoares** [comment]
Animado.... Olha, é um trampinho viu, rsrsrs...

**Comment by rafaell-lycan** [comment]
@ubiratansoares vou abrir issue pra ti :ghost: 

Falei pra um brother meu desenvolver um layout, com datepicker pra selecionar a data e com as informações.

Da pra fazer animação desse nível de água quando o usuário troca de uma para outra? (ex: de 20% para 49% animado em 200ms).

Abs

**Comment by ubiratansoares** [comment]
Fala meu velho! 

Voltei hoje do IO, e estou matando os email (e os issues tb!). Eu vou ver com o meu designer aqui da VivaReal e quem sabe ele dá um tapa visual bacana nessa aplicação pra gente ;)

Se rolar, eu monto uma versão full do app e lanço na loja, com os devidos créditos para todos! 

A gente vai se falando!

Abs

**Comment by rafaell-lycan** [comment]
Por mim fechou :ghost:
